[versions]
intellij = "2.1.0"
intellij-ce="2024.3.6"
commonmark = "0.24.0"

[plugins]
intellij = { id = "org.jetbrains.intellij.platform", version.ref = "intellij" }

[libraries]
commonmark = { group = "org.commonmark", name = "commonmark", version.ref = "commonmark" }