[versions]
# Plugins
kotlin = "2.1.20"
intellij = "2.1.0"
dotenv = "4.0.0"
# Dependencies
serialization = "1.8.+"
coroutines = "1.10.+"
kaml = "0.+"
commons = "0.1-SNAPSHOT"
tooling = "7.1.+"
# Testing
junit = "5.9.2"
mordant = "2.7.2"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
intellij = { id = "org.jetbrains.intellij.platform", version.ref = "intellij" }
dotenv = { id = "co.uzzu.dotenv.gradle", version.ref = "dotenv" }

[libraries]
kotlin-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "serialization" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json-jvm", version.ref = "serialization" }
kotlin-serialization-yaml = { group = "com.charleskorn.kaml", name = "kaml", version.ref = "kaml" }
kotlin-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core-jvm", version.ref = "coroutines" }
junit-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
mordant = { group = "com.github.ajalt.mordant", name = "mordant", version.ref = "mordant" }
commons = { group = "dev.kikugie", name = "commons", version.ref = "commons" }
gradle-tooling = { group = "org.gradle", name = "gradle-tooling-api", version.ref = "tooling" }
gradle-slf4j = { group = "org.slf4j", name = "slf4j-simple", version = "1.7.10" }

[bundles]
test = [
    "junit-api",
    "junit-engine",
    "mordant"
]