[versions]
intellij = "2.6.0"
intellij-ce = "2024.3.3"
grammarkit = "2022.3.2.2"
commonmark = "0.24.0"
semver = "1.0"

[plugins]
intellij = { id = "org.jetbrains.intellij.platform", version.ref = "intellij" }
grammarkit = { id = "org.jetbrains.grammarkit", version.ref = "grammarkit" }

[libraries]
commonmark = { group = "org.commonmark", name = "commonmark", version.ref = "commonmark" }
semver = { group = "dev.kikugie", name = "semver", version.ref = "semver" }